"""empty message

Revision ID: 52a03dd4cf97
Revises: b7ae433b21d2
Create Date: 2026-01-22 12:20:56.620323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a03dd4cf97'
down_revision = 'b7ae433b21d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cover_img', sa.String(length=255), nullable=True))

    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.drop_column('last_position')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('cover_img')
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
