"""add email verification fields to users table

Revision ID: 9377e95b2412
Revises: bc16c9fd1a92
Create Date: 2026-01-28 15:21:42.274801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9377e95b2412'
down_revision = 'bc16c9fd1a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('email_code_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_code_expires')
        batch_op.drop_column('email_code')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
