"""added trailerURL cast backdrop dirsector and some columns to Movie table

Revision ID: bc16c9fd1a92
Revises: 52a03dd4cf97
Create Date: 2026-01-23 12:15:26.301756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc16c9fd1a92'
down_revision = '52a03dd4cf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trailerUrl', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('backdrop', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('director', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cast', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('cast')
        batch_op.drop_column('director')
        batch_op.drop_column('backdrop')
        batch_op.drop_column('trailerUrl')

    # ### end Alembic commands ###
